# Generated by Django 2.1.15 on 2020-10-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpRenew', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empcolumn',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('shain_cd', models.CharField(max_length=10)),
                ('shain_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('shain_nm_k', models.CharField(blank=True, max_length=100, null=True)),
                ('adr1', models.CharField(max_length=100)),
                ('adr2', models.CharField(max_length=100)),
                ('tel1', models.CharField(max_length=13)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('keiyaku_start_date', models.DateTimeField()),
                ('keiyaku_end_date', models.DateTimeField()),
                ('genba_name', models.CharField(max_length=100)),
                ('shugyou1_to', models.IntegerField(blank=True, null=True)),
                ('shugyou2_to', models.IntegerField(blank=True, null=True)),
                ('shugyou3_to', models.IntegerField(blank=True, null=True)),
                ('shugyou4_to', models.IntegerField(blank=True, null=True)),
                ('shugyou1_from', models.IntegerField(blank=True, null=True)),
                ('shugyou2_from', models.IntegerField(blank=True, null=True)),
                ('shugyou3_from', models.IntegerField(blank=True, null=True)),
                ('shugyou4_from', models.IntegerField(blank=True, null=True)),
                ('shugyou1_break', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('shugyou2_break', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('shugyou3_break', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('shugyou4_break', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('shurou_nissu', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('shoku_name', models.CharField(max_length=100)),
                ('chingin_kbn', models.CharField(max_length=3)),
                ('chingin_dt_1', models.IntegerField(blank=True, null=True)),
                ('chingin_dt_2', models.IntegerField(blank=True, null=True)),
                ('chingin_dt_3', models.IntegerField(blank=True, null=True)),
                ('chingin_dt_4', models.IntegerField(blank=True, null=True)),
                ('next_uq_date', models.DateTimeField(blank=True, null=True)),
                ('shugyou1_kosu', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('shugyou2_kosu', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('shugyou3_kosu', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('shugyou4_kosu', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('next_uq_day_num', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('tou_str_uq_zan_num', models.CharField(max_length=50)),
                ('koyou_hoken_kbn', models.CharField(max_length=1)),
                ('shakai_hoken_kbn_cd', models.CharField(max_length=1)),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'empcolumn',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='empcol',
            options={'managed': False},
        ),
    ]
