# Generated by Django 2.1.15 on 2020-10-01 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpRenew', '0003_auto_20201001_1052'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empcol',
            table='EmpRenew_empcolumn',
        ),
    ]
