# Generated by Django 2.1.15 on 2020-10-02 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpRenew', '0004_auto_20201001_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empcolumn',
            options={'managed': True},
        ),
    ]
